In [1]:
import numpy as np

In [5]:
array = np.arange(36).reshape(9,4)
print(array)
print("-"*30)
print(array[[4, 3, 0, 6]])#兩層[]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
------------------------------
[[16 17 18 19]
 [12 13 14 15]
 [ 0  1  2  3]
 [24 25 26 27]]


In [9]:
array = np.arange(32).reshape(8,4)
print(array)
print("-"*30)
read = array[[1, 5, 7, 2], [0, 3, 1, 2]]#取[1, 5],[5, 3],[7, 1],[2, 2]
print(read)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
------------------------------
[ 4 23 29 10]


In [11]:
print(array)
print("-"*30)
print(array[:,[1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
------------------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]
 [25 26]
 [29 30]]


In [15]:
array = np.arange(10)
index = np.array([[0, 2], [1, 3]])
print(array)
print(index)
print("-"*30)
print(array[index])

[0 1 2 3 4 5 6 7 8 9]
[[0 2]
 [1 3]]
------------------------------
[[0 2]
 [1 3]]


In [25]:
#取array中最大的前N個數
array = np.random.randint(1,100,10)
print(array)
print("-"*30)
sort = array.argsort()
print(sort)
print("-"*30)
subscript = array.argsort()[-3:]
print(subscript)
print("-"*30)
max = array[subscript]
print(f'max three are {max}')

[25 48 71 97 93 82 73 91 65 35]
------------------------------
[0 9 1 8 2 6 5 7 4 3]
------------------------------
[7 4 3]
------------------------------
max three are [91 93 97]
