In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[1 2 3 4 5 6]
(6,)
1
6
int32


In [4]:
b = np.array( [[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32


In [6]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
d = np.zeros((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
e = np.full((3,3), 520)
print(e)

[[520 520 520]
 [520 520 520]
 [520 520 520]]


In [12]:
f = np.ones((2, 3, 3))
print(f)
print(f.shape)
print(f.ndim)
print(f.size)
print(f.dtype)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(2, 3, 3)
3
18
float64


In [16]:
print(b)

g = np.ones_like(b)
print(g)

h = np.zeros_like(b)
print(h)

i = np.full_like(b,520)
print(i)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[520 520 520]
 [520 520 520]]


In [23]:
j = np.random.randn()
print(j)

k = np.random.randn(3)
print(k)

l = np.random.randn(3, 3)
print(l)

m = np.random.randn(2, 3, 3)
print(m)

0.7527888760107703
[ 0.83060993 -0.30484259 -0.28832188]
[[-1.0404703  -2.38717108  0.28513285]
 [-2.08056249  0.51269068 -1.1361992 ]
 [ 0.45524511  0.75131979 -0.72232464]]
[[[ 0.91741215 -1.15724396  0.05866211]
  [-0.52300201  0.03452929  1.93735895]
  [ 0.73765448  0.8804023  -1.53816825]]

 [[ 0.89561977  1.93440826 -1.45065153]
  [ 2.27809748  0.66528331  0.22649337]
  [-0.2431153   0.44239964 -0.53269591]]]


In [21]:
k = np.random.randn(3)
print(k)

[0.60304784 1.28869525 1.26867482]
