In [16]:
import numpy as np

In [17]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
print(a+1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
b = np.random.randn(2, 5)
print(a)
print('-'*30)
print(b)
print('-'*30)
print(a+b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[-0.72643111  1.01386506 -0.82540647  0.08087344  1.64379832]
 [ 0.13401312 -0.42781974  0.04882302  1.22445281  2.60248321]]
------------------------------
[[-0.72643111  2.01386506  1.17459353  3.08087344  5.64379832]
 [ 5.13401312  5.57218026  7.04882302  9.22445281 11.60248321]]


In [20]:
c = np.arange(12).reshape(3,2,2)
d = np.random.randn(2,1)
print(c)
print('-'*30)
print(d)
print('-'*30)
print(c+d)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
------------------------------
[[0.05006043]
 [0.72471556]]
------------------------------
[[[ 0.05006043  1.05006043]
  [ 2.72471556  3.72471556]]

 [[ 4.05006043  5.05006043]
  [ 6.72471556  7.72471556]]

 [[ 8.05006043  9.05006043]
  [10.72471556 11.72471556]]]
