In [1]:
import numpy as np

In [6]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
print(a+1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
b = np.random.randn(2, 5)
print(a)
print('-'*30)
print(b)
print('-'*30)
print(a+b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[-1.3761734  -0.31210797  0.35590745 -1.1089146   0.82677317]
 [ 0.31450458  1.21191701 -0.90842537 -0.34769548  0.5551132 ]]
------------------------------
[[-1.3761734   0.68789203  2.35590745  1.8910854   4.82677317]
 [ 5.31450458  7.21191701  6.09157463  7.65230452  9.5551132 ]]
