In [15]:
import numpy as np

In [16]:
a = np.arange(10)
A = np.arange(20).reshape(4,5)
print(a)
print(a[3:9])
print('-'*30)


print(A)
print(A[0,0])
print(A[-1,2])
print(A[2])
print(A[-1])
print(A[0:-1])
print(A[0:2,2:4])
print(A[:,2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8]
------------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
17
[10 11 12 13 14]
[15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[2 3]
 [7 8]]
[ 2  7 12 17]
