In [9]:
import numpy as np

In [10]:
array = np.arange(10)
print(array)

filter = array > 5
print(filter)
print(array[filter])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]


In [11]:
#10個數字，讓大於5的數字變為1，小於等於5的數字變為0
print(array)
print("-"*30)
array[array <= 5] = 0
array[array > 5] = 1 
print(array)

[0 1 2 3 4 5 6 7 8 9]
------------------------------
[0 0 0 0 0 0 1 1 1 1]


In [14]:
#大於5的數字+520
array = np.arange(10)
print(array)
print("-"*30)
array[array > 5] += 520
print(array)

[0 1 2 3 4 5 6 7 8 9]
------------------------------
[  0   1   2   3   4   5 526 527 528 529]


In [23]:
array = np.arange(1,21).reshape(4,5)
print(array)
print("-"*30)
filter =  array > 10
print(filter)
print(array[filter])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[11 12 13 14 15 16 17 18 19 20]


In [29]:
#只將第三個column變為520(有瑕疵)
print(array)
print("-"*30)
print(array[:, 3])
print("-"*30)
filter = array[:, 3] > 5
array[array[:,3] > 5] = 520
print(array) #結果不如預期，這裡篩選的是bool值(F T T T)，所以使用array[filter]等同於[1: 4]



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
[ 4  9 14 19]
------------------------------
[[  1   2   3   4   5]
 [520 520 520 520 520]
 [520 520 520 520 520]
 [520 520 520 520 520]]


In [32]:
#只將第三個column變為520(正確)
array = np.arange(1,21).reshape(4,5)
print(array)
print("-"*30)
filter = array[:, 3] > 5
print(filter)
print("-"*30)
array[:, 3][filter] = 520
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
[False  True  True  True]
------------------------------
[[  1   2   3   4   5]
 [  6   7   8 520  10]
 [ 11  12  13 520  15]
 [ 16  17  18 520  20]]


In [36]:
array = np.array([[10, 20, 30], [50, 40, 10], [10, 1, 10]])
print(array)
print("-"*30)
filter = array > 25
print(filter)
print(array[filter])

[[10 20 30]
 [50 40 10]
 [10  1 10]]
------------------------------
[[False False  True]
 [ True  True False]
 [False False False]]
[30 50 40]


In [40]:
#找出偶數 or 小於7的數
array = np.arange(10)
print(array)
print("-"*30)
condition = (array <7) | (array % 2 == 0)
print(condition)
print(array[condition])

[0 1 2 3 4 5 6 7 8 9]
------------------------------
[ True  True  True  True  True  True  True False  True False]
[0 1 2 3 4 5 6 8]
